class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'masamba'
        self.UnzipMirrorCommand = 'masambaunzip'
        self.TarMirrorCommand = 'masambatar'
        self.ZipMirrorCommand = 'masambazip'
        self.CancelMirror = 'masambacancel'
        self.CancelAllCommand = 'masambacancelall'
        self.ListCommand = 'masambalist'
        self.StatusCommand = 'masambastatus'
        self.AuthorizedUsersCommand = 'masambausers'
        self.AuthorizeCommand = 'masambaauthorize'
        self.UnAuthorizeCommand = 'masambaunauthorize'
        self.AddSudoCommand = 'masambaaddsudo'
        self.RmSudoCommand = 'masambarmsudo'
        self.PingCommand = 'masambaping'
        self.RestartCommand = 'masambarestart'
        self.StatsCommand = 'masambastats'
        self.HelpCommand = 'masambahelp'
        self.LogCommand = 'masambalog'
        self.SpeedCommand = 'masambaspeedtest'
        self.CloneCommand = 'masambaclone'
        self.CountCommand = 'masambacount'
        self.WatchCommand = 'masambawatch'
        self.TarWatchCommand = 'masambatarwatch'
        self.DeleteCommand = 'masambadel'
        self.ShellCommand = 'masambashell'
        self.ExecHelpCommand = 'masambaexechelp'

BotCommands = _BotCommands()
